name: CI and release build

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add compiler to PATH
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: cl /O1 /nologo /std:c++20 /W4 /EHs /I ViGEmClient/include /Fegamepad-slotter.exe main.cpp ViGEmClient/src/ViGEmClient.cpp xinput.lib setupapi.lib

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: gamepad-slotter.exe

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
    - name: Download build result
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Create release draft
      uses: softprops/action-gh-release@v1
      with:
        files: gamepad-slotter.exe
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

